int _DllMainCRTStartup(void *, int, void *) { return 1; }

void __cdecl BrAbort() {}
void __cdecl BrAddHead() {}
void __cdecl BrAddTail() {}
void __cdecl BrDevAdd() {}
void __cdecl BrDevAddStatic() {}
void __cdecl BrDevBegin() {}
void __cdecl BrDevBeginVar() {}
void __cdecl BrDevCheckAdd() {}
void __cdecl BrDevContainedCount() {}
void __cdecl BrDevContainedFind() {}
void __cdecl BrDevContainedFindMany() {}
void __cdecl BrDevCount() {}
void __cdecl BrDevFind() {}
void __cdecl BrDevFindMany() {}
void __cdecl BrDevLastBeginQuery() {}
void __cdecl BrDevLastBeginSet() {}
void __cdecl BrDevRemove() {}
void __cdecl BrFailure() {}
void __cdecl BrFatal() {}
void __cdecl BrFileAdvance() {}
void __cdecl BrFileAttributes() {}
void __cdecl BrFileClose() {}
void __cdecl BrFileEof() {}
void __cdecl BrFileGetChar() {}
void __cdecl BrFileGetLine() {}
void __cdecl BrFileOpenRead() {}
void __cdecl BrFileOpenWrite() {}
void __cdecl BrFilePrintf() {}
void __cdecl BrFilePutChar() {}
void __cdecl BrFilePutLine() {}
void __cdecl BrFileRead() {}
void __cdecl BrFileWrite() {}
void __cdecl BrGetEnv() {}
void __cdecl BrImageAdd() {}
void __cdecl BrImageDereference() {}
void __cdecl BrImageLookupName() {}
void __cdecl BrImageLookupOrdinal() {}
void __cdecl BrImageReference() {}
void __cdecl BrImageRemove() {}
void __cdecl BrInsert() {}
void __cdecl BrIsAlpha() {}
void __cdecl BrIsDigit() {}
void __cdecl BrIsPrint() {}
void __cdecl BrIsSpace() {}
void __cdecl BrLastErrorGet() {}
void __cdecl BrLastErrorSet() {}
void __cdecl BrLexerAllocate() {}
void __cdecl BrLexerCommentSet() {}
void __cdecl BrLexerDumpSet() {}
void __cdecl BrLexerErrorSet() {}
void __cdecl BrLexerFree() {}
void __cdecl BrLexerPop() {}
void __cdecl BrLexerPosition() {}
void __cdecl BrLexerPushFile() {}
void __cdecl BrLexerPushString() {}
void __cdecl BrLexerTokenError() {}
void __cdecl BrLogPrintf() {}
void __cdecl BrMemAllocate() {}
void __cdecl BrMemCalloc() {}
void __cdecl BrMemCmp() {}
void __cdecl BrMemCpy() {}
void __cdecl BrMemFree() {}
void __cdecl BrMemInquire() {}
void __cdecl BrMemSet() {}
void __cdecl BrMemStrDup() {}
void __cdecl BrNamePatternMatch() {}
void __cdecl BrNewList() {}
void __cdecl BrObjectContainerFree() {}
void __cdecl BrObjectListAllocate() {}
void __cdecl BrParseFixed() {}
void __cdecl BrParseFloat() {}
void __cdecl BrParseInteger() {}
void __cdecl BrParseMatrixFixed() {}
void __cdecl BrParseMatrixFloat() {}
void __cdecl BrParseVectorFixed() {}
void __cdecl BrParseVectorFloat() {}
void __cdecl BrPrimitiveLibraryFind() {}
void __cdecl BrQsort() {}
void __cdecl BrRegistryAdd() {}
void __cdecl BrRegistryAddMany() {}
void __cdecl BrRegistryAddStatic() {}
void __cdecl BrRegistryClear() {}
void __cdecl BrRegistryCount() {}
void __cdecl BrRegistryEnum() {}
void __cdecl BrRegistryFind() {}
void __cdecl BrRegistryFindMany() {}
void __cdecl BrRegistryNew() {}
void __cdecl BrRegistryNewStatic() {}
void __cdecl BrRegistryRemove() {}
void __cdecl BrRegistryRemoveMany() {}
void __cdecl BrRegistryRemoveStatic() {}
void __cdecl BrRemHead() {}
void __cdecl BrRemTail() {}
void __cdecl BrRemove() {}
void __cdecl BrRendererFacilityFind() {}
void __cdecl BrResAdd() {}
void __cdecl BrResAllocate() {}
void __cdecl BrResCheck() {}
void __cdecl BrResChildEnum() {}
void __cdecl BrResClass() {}
void __cdecl BrResDump() {}
void __cdecl BrResFree() {}
void __cdecl BrResFreeNoCallback() {}
void __cdecl BrResIsChild() {}
void __cdecl BrResRemove() {}
void __cdecl BrResSize() {}
void __cdecl BrResSizeTotal() {}
void __cdecl BrResStrDup() {}
void __cdecl BrSScanf() {}
void __cdecl BrScratchAllocate() {}
void __cdecl BrScratchFlush() {}
void __cdecl BrScratchFree() {}
void __cdecl BrScratchInquire() {}
void __cdecl BrScratchString() {}
void __cdecl BrScratchStringSize() {}
void __cdecl BrSimpleAddHead() {}
void __cdecl BrSimpleInsert() {}
void __cdecl BrSimpleNewList() {}
void __cdecl BrSimpleRemHead() {}
void __cdecl BrSimpleRemove() {}
void __cdecl BrSprintf() {}
void __cdecl BrSprintfN() {}
void __cdecl BrStrCat() {}
void __cdecl BrStrCmp() {}
void __cdecl BrStrCpy() {}
void __cdecl BrStrICmp() {}
void __cdecl BrStrLen() {}
void __cdecl BrStrNCmp() {}
void __cdecl BrStrNCpy() {}
void __cdecl BrStrNICmp() {}
void __cdecl BrStrRChr() {}
void __cdecl BrStrToD() {}
void __cdecl BrStrToF() {}
void __cdecl BrStrToL() {}
void __cdecl BrStrToUL() {}
void __cdecl BrStringToTokenValue() {}
void __cdecl BrSwap16() {}
void __cdecl BrSwap32() {}
void __cdecl BrSwapBlock() {}
void __cdecl BrSwapFloat() {}
void __cdecl BrTVTemplateAllocate() {}
void __cdecl BrTVTemplateFree() {}
void __cdecl BrTokenCount() {}
void __cdecl BrTokenCreate() {}
void __cdecl BrTokenFind() {}
void __cdecl BrTokenFindMany() {}
void __cdecl BrTokenIdentifier() {}
void __cdecl BrTokenType() {}
void __cdecl BrTokenValueCompare() {}
void __cdecl BrTokenValueDump() {}
void __cdecl BrTokenValueQuery() {}
void __cdecl BrTokenValueQueryAll() {}
void __cdecl BrTokenValueQueryAllSize() {}
void __cdecl BrTokenValueQueryMany() {}
void __cdecl BrTokenValueQueryManySize() {}
void __cdecl BrTokenValueSet() {}
void __cdecl BrTokenValueSetMany() {}
void __cdecl BrVSScanf() {}
void __cdecl BrVSprintf() {}
void __cdecl BrVSprintfN() {}
void __cdecl BrWarning() {}
void __cdecl _BrAssert() {}
void __cdecl _BrExceptionBegin() {}
void __cdecl _BrExceptionEnd() {}
void __cdecl _BrExceptionResource() {}
void __cdecl _BrExceptionThrow() {}
void __cdecl _BrExceptionValueFetch() {}
void __cdecl _BrUAssert() {}
void __cdecl _EPI() {}
void __cdecl _M_br_object_container_addFront() {}
void __cdecl _M_br_object_container_count() {}
void __cdecl _M_br_object_container_find() {}
void __cdecl _M_br_object_container_findMany() {}
void __cdecl _M_br_object_container_remove() {}
void __cdecl _M_br_object_container_removeFront() {}
void __cdecl _M_br_object_container_tokensMatch() {}
void __cdecl _M_br_object_container_tokensMatchBegin() {}
void __cdecl _M_br_object_container_tokensMatchEnd() {}
void __cdecl _M_br_object_query() {}
void __cdecl _M_br_object_queryAll() {}
void __cdecl _M_br_object_queryAllSize() {}
void __cdecl _M_br_object_queryBuffer() {}
void __cdecl _M_br_object_queryMany() {}
void __cdecl _M_br_object_queryManySize() {}
void __cdecl _PRO() {}
