int _DllMainCRTStartup(void *, int, void *) { return 1; }

void __cdecl HostExceptionHook() {}
void __cdecl HostExceptionUnhook() {}
void __cdecl HostFarBlockFill() {}
void __cdecl HostFarBlockRead() {}
void __cdecl HostFarBlockWrite() {}
void __cdecl HostFarByteRead() {}
void __cdecl HostFarByteWrite() {}
void __cdecl HostFarDWordRead() {}
void __cdecl HostFarDWordWrite() {}
void __cdecl HostFarStringRead() {}
void __cdecl HostFarStringWrite() {}
void __cdecl HostFarWordRead() {}
void __cdecl HostFarWordWrite() {}
void __cdecl HostInfo() {}
void __cdecl HostInterruptCall() {}
void __cdecl HostInterruptHook() {}
void __cdecl HostInterruptUnhook() {}
void __cdecl HostLock() {}
void __cdecl HostRealAllocate() {}
void __cdecl HostRealBlockFill() {}
void __cdecl HostRealBlockRead() {}
void __cdecl HostRealBlockWrite() {}
void __cdecl HostRealByteRead() {}
void __cdecl HostRealByteWrite() {}
void __cdecl HostRealDWordRead() {}
void __cdecl HostRealDWordWrite() {}
void __cdecl HostRealFree() {}
void __cdecl HostRealInterruptCall() {}
void __cdecl HostRealInterruptGet() {}
void __cdecl HostRealInterruptSet() {}
void __cdecl HostRealStringRead() {}
void __cdecl HostRealStringWrite() {}
void __cdecl HostRealWordRead() {}
void __cdecl HostRealWordWrite() {}
void __cdecl HostRegistersGet() {}
void __cdecl HostSelectorAllocate() {}
void __cdecl HostSelectorAllocateAlias() {}
void __cdecl HostSelectorAllocateLinear() {}
void __cdecl HostSelectorAllocatePhysical() {}
void __cdecl HostSelectorBaseQuery() {}
void __cdecl HostSelectorBaseSet() {}
void __cdecl HostSelectorCS() {}
void __cdecl HostSelectorDS() {}
void __cdecl HostSelectorES() {}
void __cdecl HostSelectorFree() {}
void __cdecl HostSelectorLimitQuery() {}
void __cdecl HostSelectorLimitSet() {}
void __cdecl HostSelectorReal() {}
void __cdecl HostSelectorSS() {}
void __cdecl HostUnlock() {}
