int _DllMainCRTStartup(void *, int, void *) { return 1; }

void __cdecl PixelmapCopyBitsClip() {}
void __cdecl PixelmapLineClip() {}
void __cdecl PixelmapPointClip() {}
void __cdecl PixelmapRectangleClip() {}
void __cdecl PixelmapRectangleClipTwo() {}
void __cdecl _M_br_device_pixelmap_gen_copy() {}
void __cdecl _M_br_device_pixelmap_gen_copyBits() {}
void __cdecl _M_br_device_pixelmap_gen_copyDirty() {}
void __cdecl _M_br_device_pixelmap_gen_copyFrom() {}
void __cdecl _M_br_device_pixelmap_gen_copyFromDirty() {}
void __cdecl _M_br_device_pixelmap_gen_copyTo() {}
void __cdecl _M_br_device_pixelmap_gen_copyToDirty() {}
void __cdecl _M_br_device_pixelmap_gen_directLock() {}
void __cdecl _M_br_device_pixelmap_gen_directUnlock() {}
void __cdecl _M_br_device_pixelmap_gen_doubleBuffer() {}
void __cdecl _M_br_device_pixelmap_gen_doubleBufferDirty() {}
void __cdecl _M_br_device_pixelmap_gen_fill() {}
void __cdecl _M_br_device_pixelmap_gen_fillDirty() {}
void __cdecl _M_br_device_pixelmap_gen_flush() {}
void __cdecl _M_br_device_pixelmap_gen_line() {}
void __cdecl _M_br_device_pixelmap_gen_rectangle() {}
void __cdecl _M_br_device_pixelmap_gen_rectangle2() {}
void __cdecl _M_br_device_pixelmap_gen_synchronise() {}
void __cdecl _M_br_device_pixelmap_gen_text() {}
void __cdecl _M_br_device_pixelmap_gen_textBounds() {}
void __cdecl _M_br_device_pixelmap_mem_allocateSub() {}
void __cdecl _M_br_device_pixelmap_mem_copyBits() {}
void __cdecl _M_br_device_pixelmap_mem_copyDirty() {}
void __cdecl _M_br_device_pixelmap_mem_copyFrom() {}
void __cdecl _M_br_device_pixelmap_mem_copyFromDirty() {}
void __cdecl _M_br_device_pixelmap_mem_copyTo() {}
void __cdecl _M_br_device_pixelmap_mem_copyToDirty() {}
void __cdecl _M_br_device_pixelmap_mem_directLock() {}
void __cdecl _M_br_device_pixelmap_mem_directUnlock() {}
void __cdecl _M_br_device_pixelmap_mem_doubleBuffer() {}
void __cdecl _M_br_device_pixelmap_mem_doubleBufferDirty() {}
void __cdecl _M_br_device_pixelmap_mem_fill() {}
void __cdecl _M_br_device_pixelmap_mem_fillDirty() {}
void __cdecl _M_br_device_pixelmap_mem_flush() {}
void __cdecl _M_br_device_pixelmap_mem_line() {}
void __cdecl _M_br_device_pixelmap_mem_match() {}
void __cdecl _M_br_device_pixelmap_mem_originSet() {}
void __cdecl _M_br_device_pixelmap_mem_pixelAddressQuery() {}
void __cdecl _M_br_device_pixelmap_mem_pixelAddressSet() {}
void __cdecl _M_br_device_pixelmap_mem_pixelQuery() {}
void __cdecl _M_br_device_pixelmap_mem_pixelSet() {}
void __cdecl _M_br_device_pixelmap_mem_rectangleCopyFrom() {}
void __cdecl _M_br_device_pixelmap_mem_rectangleCopyTo() {}
void __cdecl _M_br_device_pixelmap_mem_rectangleFill() {}
void __cdecl _M_br_device_pixelmap_mem_rectangleStretchCopyFrom() {}
void __cdecl _M_br_device_pixelmap_mem_rectangleStretchCopyTo() {}
void __cdecl _M_br_device_pixelmap_mem_resize() {}
void __cdecl _M_br_device_pixelmap_mem_rowQuery() {}
void __cdecl _M_br_device_pixelmap_mem_rowSet() {}
void __cdecl _M_br_device_pixelmap_mem_rowSize() {}
void __cdecl _M_br_device_pixelmap_mem_synchronise() {}
void __cdecl _M_br_device_pixelmap_mem_validSource() {}
void __cdecl _M_br_device_pixelmap_null_copyBits() {}
void __cdecl _M_br_device_pixelmap_null_copyDirty() {}
void __cdecl _M_br_device_pixelmap_null_copyFrom() {}
void __cdecl _M_br_device_pixelmap_null_copyFromDirty() {}
void __cdecl _M_br_device_pixelmap_null_copyTo() {}
void __cdecl _M_br_device_pixelmap_null_copyToDirty() {}
void __cdecl _M_br_device_pixelmap_null_doubleBuffer() {}
void __cdecl _M_br_device_pixelmap_null_doubleBufferDirty() {}
void __cdecl _M_br_device_pixelmap_null_fill() {}
void __cdecl _M_br_device_pixelmap_null_fillDirty() {}
void __cdecl _M_br_device_pixelmap_null_pixelAddressQuery() {}
void __cdecl _M_br_device_pixelmap_null_pixelAddressSet() {}
void __cdecl _M_br_device_pixelmap_null_pixelQuery() {}
void __cdecl _M_br_device_pixelmap_null_pixelSet() {}
void __cdecl _M_br_device_pixelmap_null_rectangleCopyFrom() {}
void __cdecl _M_br_device_pixelmap_null_rectangleCopyTo() {}
void __cdecl _M_br_device_pixelmap_null_rectangleFill() {}
void __cdecl _M_br_device_pixelmap_null_rectangleStretchCopyFrom() {}
void __cdecl _M_br_device_pixelmap_null_rectangleStretchCopyTo() {}
void __cdecl _M_br_device_pixelmap_null_resize() {}
