#include "prim_p15.h"

#include "plib.h"
#include "renderfuncs.h"

C2_HOOK_VARIABLE_IMPLEMENT_ARRAY_INIT(local_block_d3d, primInfo_d3d_p15, 3, 0x10016ac8, {
    {
        {
            (void*)PointRender_d3d_RGB_555,
            NULL,
            "RGB 555, Z Buffered, Textured",
            &C2V(PrimitiveLibraryD3D),
            BRT_POINT,
            0,
            0,
            0x1f8,
            0x3f0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        },
        0x400,
        0x400,
        FUN_10007030,
        NULL,
        0,
    },
    {
        {
            (void*)PointRender_d3d_RGB_555,
            NULL,
            "RGB 555, Z Buffered, Interpolated Colour",
            &C2V(PrimitiveLibraryD3D),
            BRT_POINT,
            0,
            0,
            0x3878,
            0xf0,
            0,
            0x3800,
            0,
            0,
            0,
            0,
            0,
        },
        0x1,
        0x1,
        FUN_10007030,
        NULL,
        0,
    },
    {
        {
            (void*)PointRender_d3d_RGB_555,
            NULL,
            "RGB 555, Z Buffered, Interpolated Colour",
            &C2V(PrimitiveLibraryD3D),
            BRT_POINT,
            0,
            0x3800,
            0x78,
            0xf0,
            0x0,
            0x3800,
            0x3800,
            0,
            0,
            0,
            0,
        },
        0x1,
        0x0,
        FUN_10007030,
        NULL,
        0,
    },
});
