#ifndef C2_HOOKS_H
#define C2_HOOKS_H

#if defined(C2_HOOKS_ENABLED)

#if defined(_WIN32) && defined(_M_IX86)
#define C2_HOOK_CDECL __cdecl
#define C2_HOOK_FASTCALL __fastcall
#define C2_HOOK_STDCALL __cdecl
#else
#define C2_HOOK_CDECL
#define C2_HOOK_FASTCALL
#define C2_HOOK_STDCALL
#endif

#include <hooks.h>

#define C2_HOOK_FUNCTION(ADDRESS, FUNCTION) HOOK_FUNCTION(ADDRESS, FUNCTION)
#define C2_HOOK_FUNCTION_ORIGINAL(ADDRESS, FUNCTION, ORIGINAL) HOOK_FUNCTION_ORIGINAL(ADDRESS, FUNCTION, ORIGINAL)

#define C2_HOOK_VARIABLE_DECLARE(TYPE, NAME) HOOK_VARIABLE_DECLARE(TYPE, NAME)
#define C2_HOOK_VARIABLE_IMPLEMENT(TYPE, NAME, ADDRESS) HOOK_VARIABLE_IMPLEMENT(TYPE, NAME, ADDRESS)
#define C2_HOOK_VARIABLE(NAME) HOOK_VARIABLE(NAME)

#else

#define C2_HOOK_CDECL
#define C2_HOOK_FASTCALL
#define C2_HOOK_STDCALL

#define C2_HOOK_FUNCTION(ADDRESS, FUNCTION)
#define C2_HOOK_FUNCTION_ORIGINAL(ADDRESS, FUNCTION, ORIGINAL)

#define C2_HOOK_VARIABLE_DECLARE(TYPE, NAME) extern TYPE NAME;
#define C2_HOOK_VARIABLE_IMPLEMENT(TYPE, NAME, ADDRESS) TYPE NAME;
#define C2_HOOK_VARIABLE(NAME) (NAME)

#endif
#include "hooks.h"

#define C2V(NAME) C2_HOOK_VARIABLE(NAME)

#endif // C2_HOOKS_H
