name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: MinGW,  os: ubuntu-latest, cmake-args: '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw32.cmake', werror: true }
          - { name: MSVC,   os: windows-latest, werror: true }
          - { name: MSVC5,  os: windows-2025-vs2026, msvc5: true, cmake-args: '-DREC2_MATCHING=TRUE -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl', werror: false }
    steps:
    - name: Fetch rec2 sources
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Fetch MSVC11 (Visual Studio 97)
      uses: actions/checkout@v6
      if: ${{ matrix.platform.msvc5 }}
      with:
        repository: archaic-msvc/msvc500sp3
        path: msvc500
    - name: Setup MSVC11 (Visual Studio 97)
      if: ${{ matrix.platform.msvc5 }}
      shell: cmd
      run: |
        echo INCLUDE=${{ github.workspace }}\msvc500\include;${{ github.workspace }}\msvc500\atl\include;${{ github.workspace }}\msvc500\mfc\include>>%GITHUB_ENV%
        echo LIB=${{ github.workspace }}\msvc500\lib;${{ github.workspace }}\msvc500\mfc\lib>>%GITHUB_ENV%
        echo ${{ github.workspace }}\msvc500\bin>>%GITHUB_PATH%
        echo ${{ github.workspace }}\msvc500\redist>>%GITHUB_PATH%
    - name: Setup Ninja
      uses: ./.github/actions/setup-ninja
    - name: Setup modern MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      if: ${{ matrix.platform.name == 'MSVC' }}
      with:
        arch: x86
    - name: Install MinGW
      if: ${{ matrix.platform.name == 'MinGW' }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-mingw-w64-i686 g++-mingw-w64-i686
    - name: CMake (configure)
      run: |
        cmake -S . -B build -GNinja ${{ matrix.platform.cmake-args }} -DREC2_VENDORED=ON -DREC2_WERROR=${{ (matrix.platform.werror && 'ON') || 'OFF' }}
    - name: CMake (build)
      run: |
        cmake --build build ${{ matrix.platform.build-args }}
